# mochou-p/dondon/Cargo.toml

[package]
publish      = false
name         = "dondon"
edition      = "2024"
rust-version = "1.97.0"
authors      = ["mochou-p"]
description  = "dondon"
readme       = "README.md"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/mochou-p/dondon"

[dependencies]
cpal         = { version = "0.17.3", features = ["jack"] }
eframe       = "0.34.2"

